name: login_signup_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utility Package
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^1.1.1
  flutter_datetime_picker: 1.5.1
  #State management:
  get: ^4.6.5
  get_storage: ^2.1.1

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.0

  #Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.5
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #  LOCAL ASSETS
  assets:
    #    - assets/icons/brands/
    - assets/icons/transaction/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/users/
    - assets/logos/
    - assets/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
