// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6E-HGvefPbeI9rPv2tNTf28sZMJESnQ4',
    appId: '1:444681575846:web:8497614da6ae3cabbe8367',
    messagingSenderId: '444681575846',
    projectId: 'expense-app-f7a15',
    authDomain: 'expense-app-f7a15.firebaseapp.com',
    storageBucket: 'expense-app-f7a15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRCYM1m_C4HTf8wdFb0RztWtK74d2RGw0',
    appId: '1:444681575846:android:ddd606d0429f5d32be8367',
    messagingSenderId: '444681575846',
    projectId: 'expense-app-f7a15',
    storageBucket: 'expense-app-f7a15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUT4kbyL8WU5HR73VGP3zNMWzYtooIrBs',
    appId: '1:444681575846:ios:b8baf1caac36efedbe8367',
    messagingSenderId: '444681575846',
    projectId: 'expense-app-f7a15',
    storageBucket: 'expense-app-f7a15.appspot.com',
    androidClientId: '444681575846-eln77vi2u72lhl6jpucc5jrtab0mdm3u.apps.googleusercontent.com',
    iosClientId: '444681575846-iarekn5emp7rsooc1t4sk425siiqovqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignupProject',
  );

}